### ISSUE TITLE
Is there any ways to remove specific function from this queue ? 

### ISSUE THREAD

**Issue by colinsanity** [cnwhy/promise-queue-plus#6]
Hi buddy, I've encountered a little problem when using promise-queue-plus .  ~。~
I've pushed several functions at first, in some cases , I wanna remove some of em out of the queue, but it seems there's no APIs exposed to support this operations (as 'pop' or 'splice' to Javascript array) .  Will you support these operations ?  Or didn't I use properly ?   Please give me some hints, thanks a lot.

**Comment by cnwhy** [comment]
Without this API, the task added to the queue can not determine if it has been completed, so this operation is not safe

**Comment by colinsanity** [comment]
@cnwhy  I think there's no need to concern whether the task has finished or not , people who wants to do these operations must have known what will come ,  control strategies will be applied by themselves .  It's not a big deal to expose these APIs (. .)

**Comment by cnwhy** [comment]
If so, based on the "Promise" task is easy to achieve the same effect
you can refer to the following code:

```js
var Queue = require('promise-queue-plus');
queue1 = new Queue(1);

function job(removed,arg1,arg2){
    return new Promise(function(resolve,reject){
        if(removed && removed()){
            return reject(arg1 + ' has removed');
        }
        setTimeout(function(){
            resolve(arg1 + ' - ' + arg2);
        },100)
    })
}
var mark1 = 0, mark2 = 0;
var job1 = job.bind(null,function(){return mark1;})
var job2 = job.bind(null,function(){return mark2;})
var job3 = job.bind(null,null)
var job1Remove = function(){mark1 = 1}
var job2Remove = function(){mark2 = 1}

queue1.push(job1,['job1',1]).then(console.log,console.error);
queue1.push(job2,['job2',1]).then(console.log,console.error);
queue1.push(job3,['job3',1]).then(console.log,console.error);
queue1.push(job1,['job1',2]).then(console.log,console.error);
queue1.push(job2,['job2',2]).then(console.log,console.error);
queue1.push(job3,['job3',2]).then(console.log,console.error);
queue1.push(job1,['job1',3]).then(console.log,console.error);
queue1.push(job2,['job2',3]).then(console.log,console.error);
queue1.push(job3,['job3',3]).then(console.log,console.error);
queue1.start();
setTimeout(job1Remove,250)
setTimeout(job2Remove,450)
/*
job1 - 1
job2 - 1
job3 - 1
job1 has removed
job2 - 2
job3 - 2
job1 has removed
job2 has removed
job3 - 3
*/
```

The existing API, not so good to do this thing, may have increased after, but not now.
I have to think carefully.
